### ISSUE TITLE
您好，能问下bert用于这个比赛训练了多久吗？

### ISSUE THREAD

**Issue by Clitost** [zhpmatrix/Kaggle-Quora-Insincere-Questions-Classification#2]
我也是参加这个比赛的，今天偶然看到这个模型，想了解下大概需要训练多久

**Comment by zhpmatrix** [comment]
@Clitost 

印象中Fine-tuning的时间并不长，我并没有参加这个比赛，只是想测试下BERT的时候，这个比赛正好放出来，就索性拿来测试一下。

**Comment by Mariobai** [comment]
你这个代码怎么使用啊？看不懂啊？就是这个bert模型。

**Comment by zhpmatrix** [comment]
@Mariobai 

Quora的比赛是Kernel赛，应该不能用。我就是拿比赛数据测试一下效果。
